spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:4000/demo_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8484
  servlet:
    context-path: /demo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: API Documentation
    version: v1.1.0
    description: API-Service
    serverUrl: http://localhost:8484/demo/
    serverName: Server Test

jwt:
  signerKey: "vDAJ8U1Ggknl0ZcKgDt6x7i8d1UGXUL+jhdE3TrYbaC+WnCbHrec8Sdx+rpqKgOi"