spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:4000/demo_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8484
  servlet:
    context-path: /demo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: API Documentation
    version: v1.1.0
    description: API-Service
    serverUrl: http://localhost:8484/demo/
    serverName: Server Test
